function [Hd] = FilterDesigner(Fc1,Fc2,numBQ)
%FILTERDESIGNER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 20-Nov-2014 23:31:15

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N   = numBQ*2;       % Order
%Fc1 = 0.001;   % First Cutoff Frequency
%Fc2 = 3.4485;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
